import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { quickLinks, services } from "../data";
import { FaFacebookF, FaLinkedinIn } from "react-icons/fa";
import { CiTwitter } from "react-icons/ci";
import { IoLogoInstagram } from "react-icons/io";
const Footer = () => {
    return (_jsxs("div", { className: "w-full bg-apl-primary text-white h-max", children: [_jsxs("div", { className: "w-[90vw] mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10 py-4", children: [_jsxs("div", { className: "flex-1", children: [_jsx("h2", { className: "font-semibold mb-2 text-lg", children: "About Us" }), _jsx("p", { className: "text-sm text-gray-200", children: "APLE is a pioneer private sector licensee of the Nigerian Electricity Regulatory Commission, NERC for electricity distribution in Nigeria. APLE is a special purpose vehicle of the Aba Integrated Power Project for distribution of electricity to consumers within its ring-fenced Aba metropolis." })] }), _jsxs("div", { className: "flex flex-col", children: [_jsx("h2", { className: "font-semibold mb-2 text-lg", children: "Quicklinks" }), _jsx("div", { className: "flex flex-col gap-2", children: quickLinks.map((link) => (_jsx("span", { className: "text-sm text-gray-200 cursor-pointer hover:text-white", children: link.title }, link.id))) })] }), _jsxs("div", { className: "flex flex-col", children: [_jsx("h2", { className: "font-semibold mb-2 text-lg", children: "Our Services" }), _jsx("div", { className: "flex flex-col gap-2", children: services.map((service) => (_jsx("span", { className: "text-sm text-gray-200 cursor-pointer hover:text-white", children: service.title }, service.id))) })] }), _jsxs("div", { className: "flex flex-col", children: [_jsx("h2", { className: "font-semibold mb-2 text-lg", children: "Contact Info" }), _jsxs("div", { className: "flex flex-col gap-4", children: [_jsx("p", { className: "text-gray-200 text-sm", children: "Address: Suite 300,\u00A0 Aba Power Plaza, No.2 Geometric Power Road Osisioma-Aba, Abia State" }), _jsx("span", { className: "text-sm text-gray-200", children: "Phone: 07001238280 / 070022276937" }), _jsxs("div", { className: "flex items-center gap-4 *:cursor-pointer", children: [_jsx(FaLinkedinIn, {}), _jsx(CiTwitter, {}), _jsx(IoLogoInstagram, {}), _jsx(FaFacebookF, {})] })] })] })] }), _jsxs("div", { className: "w-[90vw] mx-auto border-t border-white py-4 flex justify-between items-center text-sm", children: [_jsxs("span", { children: ["\u00A9 ", new Date().getFullYear(), " Aba Power Electricity Company."] }), _jsx("span", { children: "Powered by Geometric Power" })] })] }));
};
export default Footer;
